# Build the package and publish it to PyPI after tests pass.
name: Publish to PyPI
on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Version tag
        id: get_version_tag
        run: |
          TAG=$(head CHANGELOG.md -n1 | sed -e 's/^# \[\([0-9.]\+\)\].*$/\1/g')
          echo "TAG=$TAG" >> $GITHUB_OUTPUT
    
      - name: Config git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Create tag
        run: |
          TAG=${{ steps.get_version_tag.outputs.TAG }}
          git tag -f "$TAG"
          git push origin -f --tags
  publish:
    name: publish
    needs: create_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Build package
        run: |
          python -m pip install -U pip build
          python -m build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_KEY }}